[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "project1"
version = "1.0"
description = "Project One - CIS6930 Spring 2025"
authors = [{name = "Anshita Rayalla", email = "anshita.rayalla@ufl.edu"}]
readme = "README.md"

[project.urls]
Task = "https://ufdatastudio.com/cis6930sp25/project/1"
repository = "https://github.com/Anshita382/cis6930sp25-project1"

[tool.setuptools]
py-modules = []

[tool.pytest.ini_options]
testpaths = ["tests"]
